Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: "userID-index"
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            NonKeyAttributes: []
            ProjectionType: "ALL"
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  ContactTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.contactTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: contactId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: contactId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
